reddit-seattle/seabot

package-lock.json
package.json
src/commands/helpCommands.ts
src/commands/quoteCommands.ts
src/server.ts
src/utils/constants.ts

Ron swanson quotes are used if no quote is provided.

Initial work on quote command - text overlayed on random image.

---

src/commands/joinLeaveCommands.ts
src/server.ts

Sends a DM to newly joined accounts (getTime() - createdTimeStamp) < 5 mins
#34

dm new accounts (<5 mins) on join

---

package-lock.json

Reverts reddit-seattle/seabot#36

Revert "pull master into dev because idk what happened" because i really don't know what happened

---

src/commands/helpCommands.ts
src/commands/utilCommands.ts
src/server.ts
src/utils/constants.ts

* Initial uptime / status command
* fixed number formatting for uptime and removed unused var

Release Initial uptime / status command (#39)

---

src/commands/joinLeaveCommands.ts

Update joinLeaveCommands.ts to be more readable

---

package.json
src/commands/weatherCommands.ts
src/models/WeatherModels.ts
src/utils/constants.ts

* use location names instead of just zip codes
* updates package.json to compile typescript when you run it (wild idea)

Weather updates and npm script update

---

src/commands/hueCommands.ts
src/functions/voiceChannelManagement.ts
src/server.ts

Fix voice channel feature

---

.github/workflows/build.yml
README.md
package-lock.json
package.json
src/commands/helpCommands.ts
src/commands/hueCommands.ts
src/commands/mtgCommands.ts
src/commands/rantChannelCommands.ts
src/commands/reactionCommands.ts
src/commands/rjCommands.ts
src/commands/weatherCommands.ts
src/functions/voiceChannelManagement.ts
src/models/Command.ts
src/server.ts
src/utils/constants.ts
src/utils/helpers.ts
tests/utilCommands.test.ts
tsconfig.json

Reaction commands and v13 updates

---

package.json
src/utils/helpers.ts

Run typescript locally from npm scripts

---

src/commands/helpCommands.ts
src/commands/utilCommands.ts
src/server.ts
src/utils/constants.ts

Updated whoops command formatting and argument ordering

`whoops` updates

---

src/commands/mtgCommands.ts
src/commands/rjCommands.ts
src/commands/utilCommands.ts
src/commands/weatherCommands.ts
src/server.ts
src/utils/reaccs.ts

Also got rid of prefix commands.

Improvements and stuff.

---

src/utils/reaccs.ts

this is what happens when nobody reviews your PRs

reacc stringmatch fix

---

src/utils/reaccs.ts

Added duck reacc

---

.gitignore
src/commands/databaseCommands.ts
src/commands/utilCommands.ts
src/utils/constants.ts

Fixed pluralization of days since an incident
Added missing link param to incident creation
Added optional custom secondary text to whoops command

Minor bugfixes

---

src/utils/constants.ts

fixing regex for user id

---

package-lock.json
package.json
src/commands/reactionCommands.ts
src/functions/voiceChannelManagement.ts
src/models/Command.ts
src/server.ts
src/utils/constants.ts
src/utils/helpers.ts
src/utils/reaccs.ts

* Adds auto-downvote to messages with "puyallup" in the text
* Attempts to fix URL's with `69` getting `nice'd`
* Adds support for 🗓️ mod-only react to convert Apollo event posts into scheduled server events

Reaction updates (including auto-event scheduler)

---

package-lock.json
package.json
src/commands/reportCommands.ts
src/commands/rjCommands.ts
src/server.ts
src/utils/constants.ts
src/utils/helpers.ts

Allows users to use /report to report content to moderators
Allows mods to ack or ignore report content with buttons
also updates some package versions

Adds user reporting feature

---

.github/workflows/build.yml
src/utils/reaccs.ts

- adding regex for a special reach command
- build pipeline now uses rpm installed tsc
- vulnerability updates from dependably

Minor updates

---

.github/workflows/dev_seabot-dev.yml
package.json
src/devConfig.json
webpack.config.js

Added pack:dev task to build a webpack config with devConfig.json for testing
Updated prod/dev webpack configs
Updated deployment task to only ship dist folder
Added node_modules bundled as runtime.js for easier deployment

Dev server deployment updates

---

.github/workflows/dev_seabot-dev.yml
.github/workflows/main_seabot.yml

zip deployment package

---

package.json
src/commands/slash/SlashCommandRouter.ts
src/commands/slash/index.ts
src/commands/slash/timeout/index.ts
src/commands/slash/timeout/timeout.ts

added feature to let users time themselves out
